### ISSUE TITLE
Disable wget verbose output of download progress

### ISSUE THREAD

**Issue by mloskot** [Vincit/travis-oracledb-xe#5]
First, I'd like to thank you a ton for this installer (I learned about it in https://github.com/wnameless/docker-oracle-xe-11g/issues/118#issuecomment-470049862). I have just tested w/ Travis CI and it will be  [extremely helpful during testing of SOCI library](https://github.com/wnameless/docker-oracle-xe-11g/issues/118#issuecomment-473227959).

------

I have one trivial issue: I noticed that `wget` downloading the installer archives produces very verbose progress output:

```
Saving to: `oracle-xe-11.2.0-1.0.x86_64.rpm.zip.aa'
     0K .......... .......... .......... .......... ..........  0% 2.15M 42s
    50K .......... .......... .......... .......... ..........  0% 3.33M 34s
   100K .......... .......... .......... .......... ..........  0%  230M 23s
   150K .......... .......... .......... .......... ..........  0% 4.57M 22s
   200K .......... .......... .......... .......... ..........  0%  194M 18s
   250K .......... .......... .......... .......... ..........  0%  275M 15s
   300K .......... .......... .......... .......... ..........  0% 4.40M 16s
   350K .......... .......... .......... .......... ..........  0%  186M 14s
...
```

and [~6000 lines like that](https://travis-ci.org/mloskot/soci/jobs/519750602) :-)

Would it be possible to run `wget -nv` instead of just `wget`?

**Comment by elhigu** [comment]
Yes. Very good idea :) this installer script has been a bit unstable, thats why I liked having docker image better... some times downloading files from github just failed.

**Comment by mloskot** [comment]
I see. The docker image seems still unusable /unavailable though.

**Comment by elhigu** [comment]
Fixed
